### ISSUE TITLE
How to configure this with doctrine versions : * 2.3.2

### ISSUE THREAD

**Issue by jimiero** [Payum/Payum#1000]
Hello,

I'm using Symfony 4.4* and when I try to setup as my PaymentToken as in your documentation i get this error:

**Single id is not allowed on composite primary key in entity App\Entity\PaymentToken**  

`<?php
// src/Entity/PaymentToken.php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Payum\Core\Model\Token;

/**
 * @ORM\Entity
 * @ORM\Table
 */
class PaymentToken extends Token
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

}
`

**Comment by jimiero** [comment]
I see it works if I put my app in dev mode, anyone can help?

**Comment by joesenova** [comment]
Use the following config:

```
payum:
        storages:
               ... your storage config ...

        security:
                token_storage:
                        App\Entity\Payum\PayumToken:
                                doctrine:
                                        driver: orm
```

use this entity php code:

```
<?php

namespace App\Entity\Payum;

use Doctrine\ORM\Mapping as ORM;
use Payum\Core\Model\Token;

#[ORM\Table(name: 'PAYUM_TOKEN')]
#[ORM\Entity]
class PayumToken extends Token
{
}
```
