### ISSUE TITLE
PayPal pro checkout processing error

### ISSUE THREAD

**Issue by povtasci** [Payum/Payum#130]
Hey guys, i'm getting payment failed error, how can i get error message from where i can find what is wrong in my code/config 

```
    // checkout process method
    $paymentName = 'paypal_pro_checkout';

    $storage = $this->get('payum')->getStorageForClass(
        'Sylius\Bundle\PaymentsBundle\Model\Payment',
        $paymentName
    );

    /** @var 'Sylius\Bundle\PaymentsBundle\Model\Payment' $paymentDetails */
    $paymentDetails['acct'] = xxxxxxxxxx;
    $paymentDetails['cvv2'] = xxx;
    $paymentDetails['expDate'] = "xx/xx";
    $paymentDetails['amt'] = 0.5;
    $paymentDetails['currency'] = 'USD';

    $paymentDetails->setSource($this->container->get("sylius.repository.credit_card")->find(1));
    $paymentDetails->setMethod($this->container->get("sylius.repository.payment_method")->find(5));

    $storage->updateModel($paymentDetails);

    $captureToken = $this->get('payum.security.token_factory')->createCaptureToken(
        $paymentName,
        $paymentDetails,
        'luconic_checkout_done' // the route to redirect after capture;
    );
    return $this->forward('PayumBundle:Capture:do', array(
        'payum_token' => $captureToken,
    ));
```

........................................................

```
    // checkout done method (route = luconic_checkout_done)
    $token = $this->get('payum.security.http_request_verifier')->verify($request);

    $payment = $this->get('payum')->getPayment($token->getPaymentName());

    $status = new BinaryMaskStatusRequest($token);
    $payment->execute($status);

    if ($status->isSuccess()) {
        $this->get('session')->getFlashBag()->set(
            'notice',
            'Payment success. Credits were added'
        );
    } else if ($status->isPending()) {
            $this->get('session')->getFlashBag()->set(
            'notice',
            'Payment is still pending. Credits were not added'
        );
    } else {
        // i'm getting this message
        $this->get('session')->getFlashBag()->set('error', 'Payment failed');
    }
```

........................................................

```
    // config part
    paypal_pro_checkout:
        paypal_pro_checkout_nvp:
            api:
                options:
                    username:  %paypal.express_checkout.username%
                    password:  %paypal.express_checkout.password%
                    partner:  'partner'
                    vendor:   'vendor'
                    sandbox:   %paypal.express_checkout.sandbox%
        storages:
            Sylius\Bundle\PaymentsBundle\Model\Payment:
                doctrine:
                    driver: orm
```
