### ISSUE TITLE
Paypal and TLSv1

### ISSUE THREAD

**Issue by smarques** [Payum/Payum#250]
Hi  one question... I have seen the changes on https://github.com/formapro-forks/Payum/commit/08a9c986afd1a41cc63f339810f8a4c4353a312b have been incorporated into the main repo.
But as far I can see it has not been integrated payum/paypal-express-checkout-nvp
So how do I go about making paypal work again?

Thank you for any help.
sergio

**Comment by naabys** [comment]
Updating the payum libs didn't did the trick for me. I checked the latest version of paypal php sdk and found that they remove `CURLOPT_SSL_CIPHER_LIST` from the client options if they find NSS instead of OpenSSL [see here](https://github.com/paypal/sdk-core-php/blob/namespace-5.3/lib/PayPal/Core/PPHttpConfig.php#L51). 
As far as I'm concerned, I overrode the `payum.buzz.client` service to set the option to null in BuzzClient:
```
  payum.buzz.client:
    class: Buzz\Client\ClientInterface
    factory_class: Payum\Core\Bridge\Buzz\ClientFactory
    factory_method: createCurl
    calls:
      - [setTimeout,[200]]
      # remove CURLOPT_SSL_CIPHER_LIST from options list
      - [setOption, [10083, null]]
```

hope this helps
