### ISSUE TITLE
Attempted to call method "getClientId" 

### ISSUE THREAD

**Issue by xorgxx** [Payum/Payum#272]
hi i try to set payumBundle (stable -.12)  on symfony 2.5.8

i get this error : 

```
Attempted to call method "getClientId" on class "Payum\Core\Model\Identificator" in D:\Programmation\Web\root_www\neo.app\src\Neo\PaymentBundle\Controller\PaymentController.php line 74. 
```

```
    public function prepareAction () {
        $paymentName = 'paypal_express_checkout_nvp_orn';

        $storage = $this->get ( 'payum' )
                        ->getStorage ( 'Neo\PaymentBundle\Entity\PayumOrder' )
        ;

        $order = $storage->createModel ();
        $order->setNumber ( uniqid () );
        $order->setCurrencyCode ( 'EUR' );
        $order->setTotalAmount ( 123 ); // 1.23 EUR
        $order->setDescription ( 'A description' );
        $order->setClientId ( 'anId' );
        $order->setClientEmail ( 'foo@example.com' );

        $storage->updateModel ( $order );

        $captureToken = $this->get ( 'payum.security.token_factory' )
                             ->createCaptureToken (
                                 $paymentName ,
                                 $order ,
                                 'payum_done' // the route to redirect after capture
                             )
        ;

        return $this->redirect ( $captureToken->getTargetUrl () );
    }
```

```
public function doneAction ( Request $request ) {
        $token = $this->get ( 'payum.security.http_request_verifier' )
                      ->verify ( $request )
        ;

        // $this->get('payum.security.http_request_verifier')->invalidate($token);

        $payment = $this->get ( 'payum' )
                        ->getPayment ( $token->getPaymentName () )
        ;

        $payment->execute ( $status = new GetHumanStatus( $token ) );

        $order = $token->getDetails ();

        return new JsonResponse(array(
                                    'status' => $status->getValue(),
                                    'order' => array(
                                        'client' => array(
                                            'id' => $order->getClientId(),
                                            'email' => $order->getClientEmail(),
                                        ),
                                        'number' => $order->getNumber(),
                                        'description' => $order->getCurrencyCode(),
                                        'total_amount' => $order->getTotalAmount(),
                                        'currency_code' => $order->getCurrencyCode(),
                                        'details' => $order->getDetails(),
                                    ),
                                ));
    }
```

```
twig:
    paths:
        %kernel.root_dir%/../vendor/payum/core/Payum/Core/Resources/views: PayumCore

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    payum:
                        is_bundle: false
                        type: xml
                        dir: %kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping

                        # set this dir instead if you use `payum/payum` library
                        #dir: %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping

                        prefix: Payum\Core\Model

payum:
    security:
        token_storage:
            Neo\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        Neo\PaymentBundle\Entity\PayumOrder: { doctrine: orm }

    contexts:
        paypal_express_checkout_nvp_orn:
            paypal_express_checkout_nvp:
                username:  blalbllll
                password:  VDJ879M
                signature: 31AvkHr8-fefWgQFzJjQfDY6qk-2pz
                sandbox: true
```

thank for help.
