### ISSUE TITLE
Custom api usage - doc seems wrong

### ISSUE THREAD

**Issue by jblanchon** [Payum/Payum#309]
Hi,
I think there are some mistakes on this doc =>
http://payum.org/doc/0.12/PayumBundle/custom_api_usage
(also for 0.13 and 0.14)

In The createPaypalExpressCheckoutApi method, arguments are reversed.

This code : 

```
    public function createPaypalExpressCheckoutApi()
    {
        return new Api($this->container->get('payum.buzz.client'), array(
            'username' => $this->container->getParameter('paypal.express_checkout.username'),
            'password' => $this->container->getParameter('paypal.express_checkout.password'),
            'signature' => $this->container->getParameter('paypal.express_checkout.signature'),
            'sandbox' => true
        ));
    }
```
should be something like this 

```
    /**
     * @return Api
     */
    public function createPaypalExpressCheckoutApi()
    {
        $faq = $this->site->getFaq();
        $credentials = $faq->getPaypalCredentials();

        return new Api(array(
            'username' => $this->container->getParameter('paypal.express_checkout.username'),
            'password' => $this->container->getParameter('paypal.express_checkout.password'),
            'signature' => $this->container->getParameter('paypal.express_checkout.signature'),
            'sandbox'   => true,
        ), $this->container->get('payum.buzz.client'));
    }
```
 
There is also a difference in the configuration

```
        your_context_name_here:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  NOT USED
                        password:  NOT USED
                        signature: NOT USED
                        sandbox: true
                apis:
                    - acme.payment.payum.paypal_express_checkout_api
```
should be something like this 

```
        your_context_name_here:
            paypal_express_checkout_nvp:
                username:  NOT USED
                password:  NOT USED
                signature: NOT USED
                sandbox:   true
                apis:
                    - acme.payment.payum.paypal_express_checkout_api
```

Can you tell me if I'am working with a wrong version or update the documentation 

Thank you,
Jaybe
