### ISSUE TITLE
Request GetHumanStatus{model: ArrayObject} is not supported

### ISSUE THREAD

**Issue by Falc** [Payum/Payum#475]
I am not able to configure and use the [Redsys gateway](https://github.com/crevillo/payum-redsys) in Symfony with Payum and PayumBundle, using version 1.2.0.

This is my configuration:
```yml
# app/config/payum.yml
payum:
    security:
        token_storage:
            Acme\PaymentBundle\Entity\PaymentToken:
                doctrine: orm

    storages:
        Acme\PaymentBundle\Entity\Payment:
            doctrine: orm

    gateways_v2:
        offline:
            offline: ~
        redsys:
            factory:        "redsys"
            merchant_code:  "%redsys_merchant_code%"
            terminal:       "%redsys_terminal%"
            secret_key:     "%redsys_secret_key%"
            sandbox:        "%redsys_sandbox%"
```
```yml
#app/config/services.yml
    acme_payment.redsys.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Crevillo\Payum\Redsys\RedsysGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: redsys }
```

I followed the [get it started](http://payum.org/doc/1.2.x/PayumBundle/get_it_started) and tried to do a purchase. This part (in my controller action) executes correctly:
```php
// ... payment creation code

$captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
    'redsys',
    $payment,
    'buy_finished'
);

return $this->redirect($captureToken->getTargetUrl());
```

But when I am redirected to `http://localhost:8001/payment/capture/bMfwrIS4ZVr4ChpPHE_JGBN3uK35NL7MSld-lALQWi0` (Payum\Bundle\PayumBundle\Controller\CaptureController::doAction()), an error is triggered:
```
Request GetHumanStatus{model: ArrayObject} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker. 
```

I don't know what is causing this error. The only weird thing I have found is that the redsys gateway is not registering its custom actions. This is the output `app/console payum:gateway:debug`:

```
redsys (Payum\Core\Gateway):
	Actions:
	Payum\Core\Bridge\PlainPhp\Action\GetHttpRequestAction
	Payum\Core\Action\CapturePaymentAction
	Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction
	Payum\Core\Bridge\Twig\Action\RenderTemplateAction
	Payum\Core\Action\GetCurrencyAction

	Extensions:
	Payum\Core\Extension\EndlessCycleDetectorExtension
	Payum\Core\Bridge\Psr\Log\LoggerExtension
	Payum\Core\Bridge\Psr\Log\LogExecutedActionsExtension
	Payum\Core\Extension\StorageExtension
		Storage: Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage
		Model: Acme\PaymentBundle\Entity\Payment

	Apis:
	Payum\Core\Bridge\Guzzle\HttpClient
```

Since the docs for 1.2.0 are not clear enough, I don't know if the error is caused by the configuration, *payum/core*, *PayumBundle* or *crevillo/payum-redsys*.

Stack trace.
```
[1] Payum\Core\Exception\RequestNotSupportedException: Request GetHumanStatus{model: ArrayObject} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.
    at n/a
        in ~/redsys-test/web/vendor/payum/payum/src/Payum/Core/Exception/RequestNotSupportedException.php line 57

    at Payum\Core\Exception\RequestNotSupportedException::create(object(GetHumanStatus))
        in ~/redsys-test/web/vendor/payum/payum/src/Payum/Core/Gateway.php line 99

    at Payum\Core\Gateway->execute(object(GetHumanStatus))
        in ~/redsys-test/web/vendor/payum/payum/src/Payum/Core/Action/ExecuteSameRequestWithModelDetailsAction.php line 32

    at Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction->execute(object(GetHumanStatus))
        in ~/redsys-test/web/vendor/payum/payum/src/Payum/Core/Gateway.php line 107

    at Payum\Core\Gateway->execute(object(GetHumanStatus))
        in ~/redsys-test/web/vendor/payum/payum/src/Payum/Core/Action/CapturePaymentAction.php line 25

    at Payum\Core\Action\CapturePaymentAction->execute(object(Capture))
        in ~/redsys-test/web/vendor/payum/payum/src/Payum/Core/Gateway.php line 107

    at Payum\Core\Gateway->execute(object(Capture))
        in ~/redsys-test/web/vendor/payum/payum/src/Payum/Core/Action/ExecuteSameRequestWithModelDetailsAction.php line 32

    at Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction->execute(object(Capture))
        in ~/redsys-test/web/vendor/payum/payum/src/Payum/Core/Gateway.php line 107

    at Payum\Core\Gateway->execute(object(Capture))
        in ~/redsys-test/web/vendor/payum/payum-bundle/Controller/CaptureController.php line 35

    at Payum\Bundle\PayumBundle\Controller\CaptureController->doAction(object(Request))
        in  line 

    at call_user_func_array(array(object(CaptureController), 'doAction'), array(object(Request)))
        in ~/redsys-test/web/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 139

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in ~/redsys-test/web/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in ~/redsys-test/web/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in ~/redsys-test/web/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in ~/redsys-test/web/web/app_dev.php line 32

    at require('~/redsys-test/web/web/app_dev.php')
        in ~/redsys-test/web/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php line 40
```

**Comment by makasim** [comment]
Use `gateways` option instead of `gateways_v2`. It still works.

**Comment by Falc** [comment]
That throws a config error:

```
InvalidConfigurationException in ArrayNode.php line 317: 
Unrecognized options "merchant_code, terminal, secret_key, sandbox" under payum.gateways.redsys"
```

**Comment by makasim** [comment]
something in broken than, it has to work.

**Comment by Falc** [comment]
Well, the docs tell to use `gateways_v2` in [get it started](http://payum.org/doc/1.2.x/PayumBundle/get_it_started) and [configuration reference](http://payum.org/doc/1.2.x/PayumBundle/configuration_reference). And it works since the `redsys` gateway becomes available. But it crashes in `Payum\Bundle\PayumBundle\Controller\CaptureController::doAction()`.

**Comment by makasim** [comment]
The short answer is: `gateways_v2` is prefered way as it will be the the main and the only one way to configure gateways in version 2.x (current master) but it does not work for redsys right now.  If you omit `factory` option the core factory is used. 

The gateways_v2 config should look like:

```
gateways_v2:
        offline:
            factory: offline
        redsys:
            factory: redsys
            merchant_code:  "%redsys_merchant_code%"
            terminal:       "%redsys_terminal%"
            secret_key:     "%redsys_secret_key%"
            sandbox:        "%redsys_sandbox%"
```

You have to register the redsys factory manually like this:


```
services:
    acme_payment.redsys.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Crevillo\Payum\Redsys\RedsysGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: redsys }
```

but the last code snippet does not work in 1.x
