### ISSUE TITLE
PayumPayU bundle question

### ISSUE THREAD

**Issue by demianchuk** [Payum/Payum#551]
Hi!
My name is Sergii Demianchuk!

Want to use Payum bundle for one symfony project.

I want to integrate PayPal and PayU payments. There is no problem with Paypal but
I cant install PayumPayU bundle that I am going to use.
From documentation PayumPayU bundle factory has to be added:

```
class AcmePaymentBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $payumExtension = $container->getExtension('payum');
        $payumExtension->addGatewayFactory(new PayUPaymentFactory());
    }
}
```

But it doesn't work any more. I've tried to init pay u gateway via payum builder directly - but than it demands token storage
though I added it to config

```
return (new PayumBuilder)
            ->addGatewayFactory('payu', new PayUGatewayFactory($defaultConfig))

            ->addGateway('payu', [
                'factory' => 'pau'
            ])

            ->getPayum();
```
My config:

```
payum:
    security:
        token_storage:
            AppBundle\Entity\Payment\PaymentToken: { doctrine: orm }
    storages:
        AppBundle\Entity\Payment\PaymentTest: { doctrine: orm }
    gateways:       
        payu:
            factory: payu
            environment: secure
            pos_id: xxxxx
            pos_auth_key: xxxx
            key1: xxxxxx
            key2: xxxxxx
            signature_key: xxxxx
```

So, my question is how can I integrate PayumPayU bundle? Can you help me to solve that problem?

Thank you very much.
