### ISSUE TITLE
PayPal express checkout IPN

### ISSUE THREAD

**Issue by nash4ever** [Payum/Payum#570]
Hi,
I registered an extension that will do app specific logic.
I used this code:
https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/instant-payment-notification.md

Here is my function:
```
public function onPostExecute(Context $context)
    {
        $request = $context->getRequest();
        if (false == $request instanceof Generic) {
            $this->logger->error("NOT Generic");
            return;
        }
        if (false == $request instanceof GetStatusInterface) {
            $this->logger->error("NOT GetStatusInterface");
            return;
        }

        $payment = $request->getModel();
        if (false == $payment instanceof PaymentInterface) {
            $this->logger->error("NOT PaymentInterface");
            return;
        }

        $context->getGateway()->execute($status = new GetHumanStatus($payment));

        // check the status and act accordingly
 }
```

If I call my notify URL in a browser, I get these rows in my log file:

> app. ERROR: NOT GetStatusInterface
> app. ERROR: NOT GetStatusInterface
> app. ERROR: NOT GetStatusInterface

What is the problem with my code, or token?

If I call my notify url with PayPal IPN simulator, I get this error :

> IPN was not sent, and the handshake was not verified. Please review your information.
But a new error appear in the log file.

Thanks for your help.

**Comment by makasim** [comment]
@nash4ever post the payum config

**Comment by nash4ever** [comment]
config.yml
```

payum:
    security:
        token_storage:
            XXX\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        XXX\PaymentBundle\Entity\Payment: { doctrine: orm }
        XXX\PaymentBundle\Entity\PaymentDetails: { doctrine: orm }

    gateways:
        offline:
            factory: offline
        xxx_paypal_express:
            factory: paypal_express_checkout
            username:  %paypal_express_username%
            password:  %paypal_express_password%
            signature: %paypal_express_signature%
            sandbox: %paypal_express_sandbox%
```

```
public function sendPayPalExpressCheckout(Request $request)
{
    $gatewayName = 'xxx_paypal_express';

    $amount = 1000;

    //Save to Payment table
    $storage = $this->getPayum()->getStorage(Payment::class);
    $payment = $storage->create();
    $payment->setNumber(uniqid());
    $payment->setCurrencyCode('USD');
    $payment->setTotalAmount($amount);

    $payment->setUser($this->getUser());
    $payment->setClientId($this->getUser()->getId());
    $payment->setClientEmail($this->getUser()->getEmail());
    $payment->setPaymentProvider("paypal");

    $storage->update($payment);

    //IPN settings
    $notifyToken = $this->getPayum()->getTokenFactory()->createNotifyToken($gatewayName, $payment);


    $payment->setDetails(array(
        'PAYMENTREQUEST_0_CURRENCYCODE' => 'USD'
    , 'PAYMENTREQUEST_0_AMT' => $amount
    , 'PAYMENTREQUEST_0_NOTIFYURL' => $notifyToken->getTargetUrl()
    ));
    $storage->update($payment);
    $captureToken = $this->getPayum()->getTokenFactory()->createCaptureToken(
        $gatewayName,
        $payment,
        'capture_payment_done'
    );

    return $this->redirect($captureToken->getTargetUrl());
}
```
service.yml
```
services:
    xxx.payment.payum.extension.store_notification:
        class: XXX\PaymentBundle\Payum\Extension\StoreNotificationExtension
        tags:
            - { name: payum.extension, gateway: xxx_paypal_express }
        arguments: ["@doctrine", "@logger"]
```

```
class StoreNotificationExtension implements ExtensionInterface
{
    /**
     * @var RegistryInterface
     */
    protected $doctrine;
    protected $logger;
    /**
     * @var Notify[]
     */
    protected $processedRequests;
    /**
     * @param RegistryInterface $doctrine
     */
    public function __construct($doctrine, $logger)
    {
        $this->doctrine = $doctrine;
        $this->logger = $logger;
        $this->processedRequests = array();
    }

    /**
     * {@inheritDoc}
     */
    public function onPostExecute(Context $context)
    {
        $this->logger->error("PAYPAL NotificationDetails");
        /** @var Notify $request */

        $request = $context->getRequest();
        if (false == $request instanceof Generic) {
            $this->logger->error("PAYPAL NotificationDetails: Generic");
            return;
        }
        if (false == $request instanceof GetStatusInterface) {
            $this->logger->error("PAYPAL NotificationDetails: GetStatusInterface");
            return;
        }
        $this->logger->error("PAYPAL NotificationDetails: www");
        $payment = $request->getModel();
        if (false == $payment instanceof PaymentInterface) {
            $this->logger->error("PAYPAL NotificationDetails: PaymentInterface");
            return;
        }

        $this->processedRequests[] = $request;
        $notification = new NotificationDetails();
        $request->getToken() ?
            $notification->setGatewayName($request->getToken()->getGatewayName()) :
            $notification->setGatewayName('unknown')
        ;
        $notification->setDetails($_REQUEST);
        $notification->setCreatedAt(new \DateTime());
        $this->doctrine->getManager()->persist($notification);
        $this->doctrine->getManager()->flush();
    }
```
