### ISSUE TITLE
Possibility to configure LANDINGPAGE=Billing for PaypalExpressCheckout

### ISSUE THREAD

**Issue by tchapi** [Payum/Payum#599]
Hi,

I'm using Payum throught **Sylius** > **PayumBundle** and I would like to redirect users to the credit card page directly when using PaypalExpressCheckout.

This is possible by simply adding a parameter in the `SetExpressCheckout` API call (see https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/)

Is this configurable somewhere ? Would it be easy to do or would you point me to the right file so I can submit a PR for this functionality if you think it could be merged ?

Best

**Comment by makasim** [comment]
1. you have to add paypal's specific convert payment action (it may extend the basic one) and add there this parameter (by setting it to payment details).
2. You can add a payum's extension which is waits for Convert request with expected settings. and add it there.

**Comment by tchapi** [comment]
Hi again,
I will go for the second solution with a payum extension. I haven't found anything in the docs about extensions, can you elaborate a bit so I can do this ?

I suppose I have to define a new service like this : 

```yaml
```

**Comment by frechina** [comment]
I'm also interested on the answer of this question, if anyone can help it would be very nice

**Comment by tchapi** [comment]
It's your lucky day @frechina 

```php
<?php

namespace My\WebBundle\Payum\Extension;

use Payum\Core\Extension\Context;
use Payum\Core\Extension\ExtensionInterface;
use Payum\Core\Request\Convert;

final class AddLandingPageExtension implements ExtensionInterface
{
    /**
     * @codeCoverageIgnore
     * {@inheritdoc}
     */
    public function onPreExecute(Context $context)
    {
    }

    /**
     * @codeCoverageIgnore
     * {@inheritdoc}
     */
    public function onExecute(Context $context)
    {
    }

    /**
     * {@inheritdoc}
     */
    public function onPostExecute(Context $context)
    {
        $request = $context->getRequest();

        if (false === $request instanceof Convert) {
            return;
        }

        // Now amends the result array
        $result = $request->getResult();
        $result['LANDINGPAGE'] = 'Billing'; // OR 'Login';
        $request->setResult($result);
    }
}

```

With : 

```yaml
    my_web.payum.extension.landing_page:
        class: My\WebBundle\Payum\Extension\AddLandingPageExtension
        tags:
            - { name: payum.extension, factory: paypal_express_checkout }

```

**Comment by frechina** [comment]
awesome! thank you @tchapi

**Comment by makasim** [comment]
Would it be better to overwrite the convert action itself

```yaml
payum:
  gateways:
    paypal:
      factory: paypal_express_checkout
      payum.action.convert_payment: '@your_convert_payment_action_service_id'
      # ... other fields
```
