### ISSUE TITLE
Installing payum on symfony 3

### ISSUE THREAD

**Issue by Leggy7** [Payum/Payum#613]
Cannot find on the documentation how to register the bundle on a symfony 3 project (my version is 3.2.1)
The configuration described looks like to fit an older version of symfony.

My config.yml file can't be parsed correctly unless I don't register the bundle correctly

```
payum:
    gateways:
        gateway_name:
            factory: paypal_express_checkout
            username:  username
            password:  ***
            signature: ***
```

Could you enlight me on what to register it in the AppKernel.php ?
