### ISSUE TITLE
how can I save custom fields in my payment model and receive them in 'done'?

### ISSUE THREAD

**Issue by frechina** [Payum/Payum#629]
Hi,

I have a Payment model like this, where I added a field 'externalId'

```
use Doctrine\ODM\MongoDB\Mapping\Annotations as Mongo;
use Payum\Core\Model\Payment as BasePayment;

/**
 * @Mongo\Document
 */
class Payment extends BasePayment
{
    /**
     * @Mongo\Id
     *
     * @var string $id
     */
    protected $id;

    /**
     * @Mongo\string
     *
     * @var string $externalId
     */
    protected $externalId;

    /**
     * @return string
     */
    public function getExternalId()
    {
        return $this->externalId;
    }

    /**
     * @param string $externalId
     */
    public function setExternalId($externalId)
    {
        $this->externalId = $externalId;
    }

}

```

My prepare action is as follows:

```
public function prepareAction()
    {
        $gatewayName = 'stripe_js';

        $storage = $this->get('payum')->getStorage(Payment::class);

        $payment = $storage->create();

        /** @var Payment $payment */
        $payment->setNumber(uniqid());
        $payment->setCurrencyCode('EUR');
        $payment->setTotalAmount(123); // 1.23 EUR
        $payment->setDescription('A description');
        $payment->setClientId('anId');
        $payment->setClientEmail('foo@example.com');
        $payment->setExternalId('external99');

        $storage->update($payment);

        $captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
            $gatewayName,
            $payment,
            'payments_done' 
        );

        return $this->redirect($captureToken->getTargetUrl());
    }
```

The document is correctly stored in mongo

```
{ "_id" : ObjectId("58a1c9a90bb69681008b4586"), "number" : "58a1c9a925c0a", "description" : "A description", "clientEmail" : "foo@example.com", "clientId" : "anId", "totalAmount" : NumberLong(123), "currencyCode" : "EUR", "externalId" : "external99" }
```

However, in my done action I didn't get the externalId value

```
public function doneAction(Request $request)
    {
        $token = $this->get('payum')->getHttpRequestVerifier()->verify($request);

        $gateway = $this->get('payum')->getGateway($token->getGatewayName());

        $gateway->execute($status = new GetHumanStatus($token));
        $payment = $status->getFirstModel();

        dump($payment); // TODO: externalId is null

        return new JsonResponse(array(
            'status' => $status->getValue(),
            'payment' => array(
                'total_amount' => $payment->getTotalAmount(),
                'currency_code' => $payment->getCurrencyCode(),
                'details' => $payment->getDetails(),
            ),
        ));
    }
```

do you know what am I doing wrong?

This is my configuration
```

payum:
    security:
        token_storage:
            PaymentsBundle\Document\PaymentToken: { doctrine: mongodb }

    storages:
        PaymentsBundle\Document\Payment: { doctrine: mongodb }

    gateways:
        paypal_express_checkout:
            factory: paypal_express_checkout
            username: "%paypal.express_checkout.username%"
            password: "%paypal.express_checkout.password%"
            signature: "%paypal.express_checkout.signature%"
            sandbox: %paypal.express_checkout.sandbox%

        stripe_js:
            factory: stripe_js
            publishable_key: "%stripe.publishable_key%"
            secret_key: "%stripe.secret_key%"
```

Thank you!
