### ISSUE TITLE
how is the extensions loaded?

### ISSUE THREAD

**Issue by frechina** [Payum/Payum#631]
I want to play with payum extensions, like CreateCustomerExtension. However, I don't know how to load it. In fact, CreateCustomerExtension seems to be loaded by default and I don't know how to disable it.

I don't see any reference of this in the documentation.

Could anyone tell me how to create/load/disable extensions? And how them work? 

Thank you.

**Comment by makasim** [comment]
using a gateway config which is passed to a gateway factory. Every config's key that has prefix `payum.extension` is treated as extension. 

```php
<?php
/** @var Payum $payum */
$payum = (new PayumBuilder())
    ->addDefaultStorages()
    ->addGateway('aGateway', [
        'factory' => 'offline',
        
       // add a new one, or overwrite an existing extension
       'payum.extension.foo' = new FooExtension(),
    ])

    ->getPayum()
;
```

Similar stuff could be done in symfony bundle:

```yaml
payum:
  gateway:
    aGateway:
      factory: offline
      payum.extension.foo: "@anExtensionServiceId"
```
