### ISSUE TITLE
Problem creating custom gateway using dynamic gateways

### ISSUE THREAD

**Issue by liamsorsby** [Payum/Payum#650]
Hi again,

I'm developing a custom gateway for CardNet, and I have managed to register the gateway. However, when I register the gateway it seems to inherit actions from a different gateway.
``` yaml
cardnet (Payum\Core\Gateway):
        Actions:
        Payum\Core\Bridge\Symfony\Action\GetHttpRequestAction
        Payum\Core\Bridge\Symfony\Action\ObtainCreditCardAction
        Payum\Core\Action\CapturePaymentAction
        Payum\Core\Action\AuthorizePaymentAction
        Payum\Core\Action\PayoutPayoutAction
        Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction
        Payum\Core\Bridge\Twig\Action\RenderTemplateAction
        Payum\Core\Action\GetCurrencyAction
        Payum\Core\Action\GetTokenAction
        Payum\Paypal\ProCheckout\Nvp\Action\CaptureAction
        Payum\Paypal\ProCheckout\Nvp\Action\RefundAction
        Payum\Paypal\ProCheckout\Nvp\Action\ConvertPaymentAction
        Payum\Paypal\ProCheckout\Nvp\Action\StatusAction

        Extensions:
        Payum\Bundle\PayumBundle\Profiler\PayumCollector
        Payum\Core\Extension\GenericTokenFactoryExtension
        Payum\Core\Bridge\Psr\Log\LoggerExtension
        Payum\Core\Bridge\Psr\Log\LogExecutedActionsExtension
        Payum\Core\Extension\StorageExtension
                Storage: Payum\Core\Bridge\Doctrine\Storage\DoctrineStorage
                Model: App\PaymentBundle\Entity\PaymentDetails
        Payum\Core\Extension\EndlessCycleDetectorExtension

        Apis:
        Payum\Core\Bridge\Httplug\HttplugClient
        Payum\Paypal\ProCheckout\Nvp\Api
```

I am using the 2.0 version of the bundle and I have registered the gateway using the service in symfony:
```yaml
app.payment.cardnet.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [App\CardNetHosted\CardnetHostedGatewayFactory]
        tags:
           - { name: payum.gateway_factory_builder, factory: cardnethosted }
```

Are there any missing steps here as I am at a loose end as to why It's registering the Paypal Actions and not the CardNet Actions I've implemented. I have checked the namespacing which all seems to be correct.

If you know of anything that I could have missed it would be great.

Thanks,
Liam

**Comment by makasim** [comment]
I did not notice anything weird. Could you please post a payum bundle config?

**Comment by liamsorsby** [comment]
@makasim The config is below:

```yaml
payum:
    security:
        token_storage:
            App\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        App\PaymentBundle\Entity\PaymentDetails: { doctrine: orm }

    dynamic_gateways:
        sonata_admin: false
        config_storage:
            App\PaymentBundle\Entity\GatewayConfig: { doctrine:orm }
```

To make things simpler I have disabled Paypal Pro and PayPal express from the config (database) but the results are still identical.

I've just removed them from composer which has resulted in the following error using 
app/console payum:gateway:debug

```cmd
  [Payum\Core\Exception\InvalidArgumentException]
  Gateway factory "paypal_pro_checkout" does not exist.

```

This was after clearing the dev and prod cache.
