### ISSUE TITLE
CoreGatewayFactory try to call gateway's string config parameter that accidentally same as name of php built-in function

### ISSUE THREAD

**Issue by Great-Antique** [Payum/Payum#692]
I have a config of Payum gateways like this (in Symfony):
```yaml
payum:
    security:
...
    storages:
...
    gateways:
        paypal:
...
        safecharge:
            factory: safecharge
            merchant_id: "%safecharge_merchant_id%"
            merchant_site_id: "%safecharge_merchant_site_id%"
            merchant_secret_key: "%safecharge_merchant_secret_key%"
            sandbox: "%safecharge_sandbox%"
            hash_algorithm: md5
```

When I run application I have an issue
```
Warning: md5() expects parameter 1 to be string, object given
```

Stack:
```php
...
// vendor/payum/core/Payum/Core/CoreGatewayFactory.php line 55
$this->buildClosures($config);
...
// vendor/payum/core/Payum/Core/CoreGatewayFactory.php line 204
$config[$name] = call_user_func($value, $config);
```
So `CoreGatewayFactory` try to run `md5($config)` where `$config` is an object.

```
// dump($config);
...
    "merchant_id" => "..."
    "merchant_site_id" => "..."
    "merchant_secret_key" => "..."
    "sandbox" => true
    "hash_algorithm" => "md5"
    "payum.extension.token_factory" => GenericTokenFactoryExtension {#505 ▶}
    "payum.security.token_storage" => DoctrineStorage {#490 ▶}
    // and others
...
```
