### ISSUE TITLE
Adding extension to Core Factory

### ISSUE THREAD

**Issue by jmiridis** [Payum/Payum#736]
I have created a custom gateway using the core factory but I can't find any documentation on how to add the storage extension. Is that possible at all?

Here my service config:

```yaml
payum:
    security:
        token_storage:
            PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        PaymentBundle\Entity\PaymentDetails: { doctrine: orm }

    gateways:
        bfsSepa:
            factory: core
            payum.action.capture: "@payment.bfs_sepa.capture"
            payum.action.status: "@payment.bfs_sepa.status"
            payum.api: "@payment.api.bfs.sepa"
```
