### ISSUE TITLE
Composer error `The child node "security" at path "payum" must be configured.` (Symfony Bundle)

### ISSUE THREAD

**Issue by ThomasLandauer** [Payum/Payum#787]
When doing
```bash
composer require "payum/payum-bundle" "payum/offline" "php-http/guzzle6-adapter"
```
...as explained at https://github.com/Payum/Payum/blob/master/docs/symfony/get-it-started.md

I'm getting this error (Symfony 4.2.1):

> Executing script cache:clear [KO]                                                                                                                                 
 [KO]                                                                                                                                                             
Script cache:clear returned with error code 1                                                                                                                     
!!                                                                                                                                                                
!!  In ArrayNode.php line 228:
!!                                                                   
!!    The child node "security" at path "payum" must be configured.

This is the same issue as https://github.com/Payum/Payum/issues/741 but I'm opening a new, since the other was falsely labelled as "question" and closed.
However, when following the "Get it started" documentation leads to an error message, it's certainly a bug.

**Comment by makasim** [comment]
Do you have something like this in the config? 

```
#app/config/config.yml

payum:
    security:
        token_storage:
            Acme\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        Acme\PaymentBundle\Entity\Payment: { doctrine: orm }
            
    gateways:
        offline:
            factory: offline
```
