### ISSUE TITLE
Symfony EventDispatcherExtension configuration error

### ISSUE THREAD

**Issue by grekpg** [Payum/Payum#821]
I try add to config payum evens extension

```
payum.extension.event_dispatcher:
  class: Payum\Core\Bridge\Symfony\Extension\EventDispatcherExtension
  arguments: ["@event_dispatcher"]
  tags:
    - { name: payum.extension, all: true, prepend: false }
```

get error

Argument 1 passed to Payum\Core\Gateway::addExtension() must implement interface Payum\Core\Extension\ExtensionInterface, string given, called in /application/vendor/payum/core/Payum/Core/CoreGatewayFactory.php on line 249

**Comment by grekpg** [comment]
I found working solution 

```
payum.extension.event_dispatcher:
  class: Payum\Core\Bridge\Symfony\Extension\EventDispatcherExtension
  arguments: ["@event_dispatcher"]
  public: true
  tags:
    - { name: payum.extension, all: true, prepend: true }

```

change prepend: false  to prepend: true
