### ISSUE TITLE
CaptureController has no container set, did you forget to define it as a service subscriber?

### ISSUE THREAD

**Issue by carlos-mg89** [Payum/Payum#841]
So it looks like I'm almost done with the setup of Payum with Stripe gateway under Symfony 5.

- The prepare and done actions are created and working at the PaymentController
- Payment and PaymentToken database tables are created and I'm seeing new rows added
- The config file packages/payum.yaml is configured as well with the stripe_checkout gateway and its publishable_key and secret_key entries too

However there seems to be an issue when setting up the CaptureController.

I included the following code in config/routes.yaml and tried as well config/routes/payum.yaml:
```
payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"
```

But I'm receiving this error:
`"Payum\Bundle\PayumBundle\Controller\CaptureController" has no container set, did you forget to define it as a service subscriber?`

I understand that the CaptureController isn't working, but I just don't know what am I missing. Since I followed the steps in https://github.com/Payum/Payum/blob/master/docs/symfony/get-it-started.md

Just in case, this is my PaymentController:

```
class PaymentController extends BaseController
{
    /**
     * @Route("/prepare")
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function prepareAction(Payum $payum)
    {
        $gatewayName = 'stripe_checkout';
        $storage = $payum->getStorage('App\Entity\Payment');

        /** @var $payment Payment */
        $payment = $storage->create();
        $payment->setNumber(uniqid());
        $payment->setCurrencyCode('EUR');
        $payment->setTotalAmount(123); // 1.23 EUR
        $payment->setDescription('TEST PLAN');
        $payment->setClientId($this->getLoggedCompany()->getId());
        $payment->setClientEmail($this->getLoggedCompany()->getOwner()->getEmail());
        $payment->setCreatedAt(new \DateTime());
        $storage->update($payment);

        $captureToken = $payum->getTokenFactory()->createCaptureToken(
            $gatewayName,
            $payment,
            'app_payment_done'
        );

        return $this->redirect($captureToken->getTargetUrl());
    }

    /**
     * @Route("/done")
     *
     * @param Request $request
     * @return JsonResponse
     * @throws \Exception
     */
    public function doneAction(Request $request, Payum $payum)
    {
        $token = $payum->getHttpRequestVerifier()->verify($request);
        $gateway = $payum->getGateway($token->getGatewayName());

        // You can invalidate the token, so that the URL cannot be requested any more:
        // $this->get('payum')->getHttpRequestVerifier()->invalidate($token);

        // Once you have the token, you can get the payment entity from the storage directly.
        // $identity = $token->getDetails();
        // $payment = $this->get('payum')->getStorage($identity->getClass())->find($identity);

        // Or Payum can fetch the entity for you while executing a request (preferred).
        $gateway->execute($status = new GetHumanStatus($token));
        $payment = $status->getFirstModel();

        // Now you have order and payment status

        return new JsonResponse(array(
            'status' => $status->getValue(),
            'payment' => array(
                'total_amount' => $payment->getTotalAmount(),
                'currency_code' => $payment->getCurrencyCode(),
                'details' => $payment->getDetails(),
            ),
        ));
    }
}
```

**Comment by carlos-mg89** [comment]
Perhaps I wrote this issue in the wrong project and I should have done it in Payum/PayumBundle. However, I found the solution over here: https://github.com/Payum/PayumBundle/issues/507

Just write this in your config/services.yaml:

```
services:
    Payum\Bundle\PayumBundle\Controller\AuthorizeController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\CancelController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\CaptureController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\NotifyController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\PayoutController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\RefundController:
        calls:
            - method: setContainer
              arguments: ['@service_container']

    Payum\Bundle\PayumBundle\Controller\SyncController:
        calls:
            - method: setContainer
              arguments: ['@service_container']
```
