### ISSUE TITLE
Guzzle 7

### ISSUE THREAD

**Issue by PandyLegend** [Payum/Payum#899]
My software requires Guzzle 7 but it seems this is not yet supported so I get the following error:

> The httplug.client could not be guessed. Install one of the following packages: php-http/guzzle6-adapter. You can also overwrite the config option with your implementation.

Can this be added as it is the latest stable version of Guzzle?

Alternatively, how would I overwrite the config option to use Guzzle 7?

Thanks

**Comment by pierredup** [comment]
@PandyLegend Guzzle 7 support will come in the next release (See #900).

But for now, you change use it by overwriting the `httplug.client` config in your gateway config class

```php
$config->defaults([
    'httplug.client' => function (ArrayObject $config) {
        return new \Http\Adapter\Guzzle7\Client();
    }
]);

**Comment by PandyLegend** [comment]
I use the Symfony bundle so don't have a gateway config class. 
However `payum.http_client: '@\Http\Adapter\Guzzle7\Client'` in the payum.yaml does the job.

**Comment by PandyLegend** [comment]
Actually, scrub that. It didn't work.

> Payum\Core\Bridge\Httplug\HttplugClient::__construct(): Argument #1 ($client) must be of type Http\Client\HttpClient, string given, called in /var/www/vhosts/sandbox.legendbdsm.com/vendor/payum/core/Payum/Core/CoreGatewayFactory.php on line 133

I guess i am doing something wrong in the yaml

**Comment by pierredup** [comment]
I think depending on how you configured the service, will cause that error. The following config should work:

```yaml

services:
    Http\Adapter\Guzzle7\Client:
        public: true

payum:

    # ...

    gateways:
        core:
            payum.http_client: '@Http\Adapter\Guzzle7\Client'

        # ...


```
