### ISSUE TITLE
Update Symfony instalation docs

### ISSUE THREAD

**Issue by Tetragramat** [Payum/Payum#918]
After updating `doctrine/doctrine-bundle` to version 2 I got "ID field missing from entity PaymentToken".
This configuration should be mentioned in instalation docs:

```yaml
orm:
    entity_managers:
        default:
            mappings:
                payum:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping'
                    # set this dir instead if you use `payum/payum` library
                    #dir: '%kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping'
                    prefix: 'Payum\Core\Model'
```
source: https://github.com/Payum/Payum/issues/789#issuecomment-496572317
